### ISSUE TITLE
createPreloadPlugin 生成的文件会错误的把函数传参进行导出

### ISSUE THREAD

**Issue by iamxiyang** [csj8520/vite-plugin-utools-helper#2]
### 复现步骤：
克隆作者自己的项目 https://github.com/csj8520/utools-plugin-tinypng/tree/master

#### 安装依赖
```bash
pnpm install
```
#### 构建项目
```bash
pnpm start
```

查看 `dist/preload.js `  会发现在最后一行额外多了**data** 的导出，这个 data 其实是 **writeFile** 方法的第二个参数。

如果修改 `src/preload/index.ts`  ，在任意方法上添加多个传参，会发现所有包含多个的参数都会被错误的收集、导出。

假设在 `src/preload/index.ts`  添加
```ts
export function testA(a1: any, a2: any, a3: any) {
  return { a1, a2, a3 }
}
```
查看 `dist/preload.js ` ，发现最后不止有 testA、还有 a2、a3，这是不符合预期的。

### 修复建议：

是 `mlly` 某个版本行为发生了变化，可以考虑对 `declaration` 只收集 `name`

**Comment by csj8520** [comment]
感谢 pr，已发布新版本
